### ISSUE TITLE
How to configure NAS Web Station ?

### ISSUE THREAD

**Issue by LionelPaulus** [tdemalliard/t411.syno.dlm#2]
Hi,

I'm trying to install your package on my Synology but it doesn't work, when I try to DL something, I've got the error _HTTPS download task (t411.syno.php) failed_
I think it's due to my Web Station configuration, what am I supposed to do in Virtual Host section ?
Here is what I've configured (I've also tried to replace **localhost** by **127.0.0.1**):
![image](https://cloud.githubusercontent.com/assets/789782/25285246/dfe504b8-26b9-11e7-9857-7acb9374ca02.png)

PS: I've correctly added **t411.syno.php** in the web folder.

Thanks in advance.

Regards,
Lionel

**Comment by tdemalliard** [comment]
Hi!
I set up the web station a long time ago... I think that I only activate it and leave everything as default. I did not set any virtual host as shown on the screenshot.
![image](https://cloud.githubusercontent.com/assets/3911087/25286241/1848b694-268b-11e7-8e93-5635a81e53f6.png)


To test that the webstation works correctly, open this address in your browser and a file should be offert to download:
https://[IP or address of your nas]/t411.syno.php
Where [IP or address  of your nas] should be replaced by the ip or address you are using to connect to your nas to use it.
The file to download is to be trashed, but if you got the download prompt, that means that it is working :+1: 

T.

**Comment by LionelPaulus** [comment]
Thanks for your fast answer !
You are right, no need to configure a Virtual Host.
I've found the problem: the PHP file didn't worked because I didn't activated the curl extension in **Web Station > PHP Settings > curl**. You should perhaps precise this in the readme ?

Now everything works perfectly, thanks a lot for your work 👏

**Comment by tdemalliard** [comment]
I am glad that it is now working for you. 

I will add the curl instruction to the readme.

Have a nice weekend :)
T.

**Comment by LionelPaulus** [comment]
Perfect !
Thanks, have a nice weekend too :)
