### ISSUE TITLE
Remove intermediary php script

### ISSUE THREAD

**Issue by pinonpierre** [tdemalliard/t411.syno.dlm#3]
Why don't do like "T411.ai.dlm 1.0.7" (http://www.nas-forum.com/forum/files/file/590-t411aidlm)?

With this plugin, we don't have any intermediary php script.

Regards,

**Comment by tdemalliard** [comment]
Because back in the time, I did quick and simple for my own use, and It is still working as expected : listing torrents.
Regards,
